"""add job_url

Revision ID: c4497df38a4d
Revises: 4f7b34654570
Create Date: 2026-03-09 23:08:05.010859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4497df38a4d'
down_revision: Union[str, Sequence[str], None] = '4f7b34654570'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('job_url', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'jobs', ['job_url'])
    op.drop_column('jobs', 'match_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('match_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'jobs', type_='unique')
    op.drop_column('jobs', 'job_url')
    # ### end Alembic commands ###
